enyo.depends(
	"webos.js",
	"VirtualKeyboard.js",
	"SymKey.js",
	"LunaBindings.js",
	"ServiceRequest.js",
	"BackGesture.js",
	"ProgressOrb.js",
	"ProgressOrb.css",
	"NumberPad.js",
	"CrossAppUI.js",
	"FilePicker.js",
	"AppMenu.js",
	"AppMenu.css",
	"HtmlContent.js",
	"ModalDialog.js",
	"WebView.js"
);
